# fly.toml app configuration file generated for linkr on 2024-04-27T22:13:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linkr'
primary_region = 'jnb'

[build]
  
[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  force_https = true

  [[services.ports]]
      handlers = ["http", "tls"]
      port = 443

  [[services.port]]
      handlers = ["http"]
      port = 80

[[vm]]
  size = 'shared-cpu-1x'
